name: Determine Tests Bot
on:
  workflow_run:
    workflows: 
        - Verify Changes
    types:
        - requested
 
jobs:
  add-comment-to-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions: write-all
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Get Recommended Tests
        run: |
            
            {
                echo 'tests_from_script<<EOF'
                ./.github/scripts/check-changes.sh
                echo EOF
            } >> "$GITHUB_ENV"
            
            echo "rec_tests=Hi, I am a friendly algorithm to help determine which tests you brok.. erm, modified. I suggest you run these! \n" >> $GITHUB_ENV
      - name: Add comment to PR
        
    #     uses: actions/github-script@v7
    #     with:
    #       github-token: {{ secrets.PAT_TOKEN }}
    #       script: |
    #         if (process.env.tests_from_script != '') {
    #             github.rest.issues.createComment({
    #             owner: context.repo.owner,
    #             issue_number: context.issue.number,
    #             repo: context.repo.repo,
    #             body: "process.env.rec_tests + process.env.tests_from_script"
    #             })
    #         }
        run: |
            PR_NUMBER=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
            | jq '.[] | select(.head.sha == "${{ github.event.workflow_run.head_commit_id }}") | .number' | head -n 1)


            response=$(curl -s -o response.json -w "%{http_code}" -X POST \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} " \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"body": "'"$rec_tests $tests_from_script"'"}' \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments")

            if [[ "$response" -lt 200 || "$response" -gt 300 ]]; then
                echo "Failed to post the comment. HTTP response code: $response"
                cat response.json
                exit 1  
            fi

        #   script: |
        #     if (process.env.tests_from_script != '') {
        #         github.rest.issues.createComment({
        #         owner: context.repo.owner,
        #         issue_number: context.issue.number,
        #         repo: context.repo.repo,
        #         body: process.env.rec_tests + process.env.tests_from_script
        #         })
        #     }